### ISSUE TITLE
Extensions not loading

### ISSUE THREAD

**Issue by SunflowerFuchs** [Ulauncher/ext.ulauncher.io#1]
A connection error occurs while trying to load the extension list on [https://ext.ulauncher.io](https://ext.ulauncher.io).

Here's the error copied from my browsers console:
`Failed to load https://owd2rwb5be.execute-api.us-east-1.amazonaws.com/prod/extensions: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://ext.ulauncher.io' is therefore not allowed access. The response had HTTP status code 502. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by gornostal** [comment]
That's weird. I checked the website 10 hours ago and as you said it wasn't working because of the CORS error.
Now it is working, although I didn't make any changes.

Anyway, thanks for reporting this issue. I'll keep an eye on it.

**Comment by ZaLiTHkA** [comment]
I just came to report this very same issue now.. I haven't actually looked at the extensions list before, so I'm not sure when this started happening.

from what I can tell by the documentation, it sounds like Amazon AWS doesn't have CORS enabled by default, but if you set up the extensions site like this from the start, then I'm pretty sure you would've enabled it anyway.. maybe there's something funky happening on Amazon's side then?

**Comment by gornostal** [comment]
I'm using AWS Lambda and it tend to crash like this lately.
Working on a fix now...

**Comment by gornostal** [comment]
fixed
