### ISSUE TITLE
401 error when submitting a extension

### ISSUE THREAD

**Issue by gumbarros** [Ulauncher/ext.ulauncher.io#55]
### Steps to reproduce
1.Submit a new extension

### Current behavior
When submiting a extension a 401 error is given.

### Expected behavior
A extension should be submitted

### Screenshots
![image](https://user-images.githubusercontent.com/52143624/216791857-0f239406-f5d0-460b-8940-4ca46e399a4d.png)

**Comment by friday** [comment]
Duplicate of https://github.com/Ulauncher/ext-api.ulauncher.io/issues/18

**Comment by gornostal** [comment]
Sorry for the inconvenience.
The issue is fixed now. I was able to submit a new extension.
